"""new enum

Revision ID: 4c8e3672cac5
Revises: e1a879b68fd1
Create Date: 2024-10-13 00:51:23.152461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c8e3672cac5'
down_revision = 'e1a879b68fd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobile_money_deposits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposit_from', sa.Enum('chips', 'bar', 'pool_table', name='depositfromenum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobile_money_deposits', schema=None) as batch_op:
        batch_op.drop_column('deposit_from')

    # ### end Alembic commands ###
