"""new enum

Revision ID: 524df22a4ca8
Revises: 4c8e3672cac5
Create Date: 2024-10-13 00:52:05.807628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524df22a4ca8'
down_revision = '4c8e3672cac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobile_money_deposits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date_of_deposit', sa.Date(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('deposit_from', sa.Enum('chips', 'bar', 'pool_table', name='depositfromenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mobile_money_deposits')
    # ### end Alembic commands ###
