"""d

Revision ID: e1a879b68fd1
Revises: 9cdfc3bb0db2
Create Date: 2024-10-11 12:19:52.642093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a879b68fd1'
down_revision = '9cdfc3bb0db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobile_money_deposits', schema=None) as batch_op:
        batch_op.drop_constraint('mobile_money_deposits_amount_key', type_='unique')
        batch_op.drop_constraint('mobile_money_deposits_date_of_deposit_key', type_='unique')
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobile_money_deposits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('mobile_money_deposits_date_of_deposit_key', ['date_of_deposit'])
        batch_op.create_unique_constraint('mobile_money_deposits_amount_key', ['amount'])

    # ### end Alembic commands ###
